export const metadata = {
    title: 'Contacts|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Contactpage = () => {
    return (
        <div>
           Contactpage 
        </div>
    );
};

export default Contactpage;