import ContactBanner from "@/components/ContactBanner";

export const metadata = {
    title: 'Contacts|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Contactpage = () => {
    return (
        <div>
          <ContactBanner/>
        </div>
    );
};

export default Contactpage;