export const metadata = {
    title: 'Events|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Event = () => {
    return (
        <div>
           Event 
        </div>
    );
};

export default Event;