import AboutSave from "@/components/AboutSave";
import AboutSlider from "@/components/AboutSlider";

export const metadata = {
    title: 'AboutUs|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const AboutUs = () => {
    return (
        <div>
           <AboutSlider/>
           <AboutSave/>
        </div>
    );
};

export default AboutUs;