import AboutMeet from "@/components/AboutMeet";
import AboutSave from "@/components/AboutSave";
import AboutSlider from "@/components/AboutSlider";

export const metadata = {
    title: 'AboutUs|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const AboutUs = () => {
    return (
        <div className="overflow-x-hidden overflow-y-hidden">
           <AboutSlider/>
           <AboutSave/>
           <AboutMeet/>
        </div>
    );
};

export default AboutUs;