import BannerMenu from "@/components/BannerMenu";
// import Bestpizza from "@/components/Bestpizza";

export const metadata = {
    title: 'Menu|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Menupage = () => {
    return (
        <div>
          <BannerMenu/>
          {/* <Bestpizza/> */}
        </div>
    );
};

export default Menupage;