export const metadata = {
    title: 'Menu|Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Menupage = () => {
    return (
        <div>
           Menupage 
        </div>
    );
};

export default Menupage;