


import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Notifications from '@/components/Notifications'
import Footer from '@/components/Footer'






const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Food Ordering Zone',
  description: 'Generated by create next app',
}

 const RootLayout=({ children })=>{
 
  return (
    <html lang="en">
   
      <body className={inter.className}>
        <Notifications/>
        <Navbar/>
       
        {children}
        <Footer/>
        </body>
        
    </html>
  )
}
export default RootLayout;
