export const metadata = {
    title: 'Blog | Food Ordering Zone',
    description: 'Generated by create next app',
  }

const Blogpage = () => {
    return (
        <div>
           Blogpage 
        </div>
    );
};

export default Blogpage;